//Check SensysEthernetInterface
#define SENSYS_MSG_TYPE_EVENT						"event"
#define SENSYS_MSG_TYPE_WATCHDOG					"watchdog"
#define SENSYS_MSG_TYPE_DIAGNOSTIC					"diagnostic"

#define SENSYSMSG_EVENT_SENSORID					"sensorId"
#define SENSYSMSG_EVENT_TIMESTAMP					"timestamp"
#define SENSYSMSG_EVENT_STATUS						"status"
#define SENSYSMSG_EVENT_ADDRESS1					"address1"
#define SENSYSMSG_EVENT_SUBCHANNEL					"subchannel"
#define SENSYSMSG_EVENT_ADJUSTED					"adjusted"
#define SENSYSMSG_EVENT_DIRECTION					"direction"

#define SENSYSMSG_WATCHDOG_SENSORID					"sensorId"
#define SENSYSMSG_WATCHDOG_TIMESTAMP				"timestamp"
#define SENSYSMSG_WATCHDOG_STATUS					"status"
#define SENSYSMSG_WATCHDOG_ADDRESS1					"address1"
#define SENSYSMSG_WATCHDOG_SUBCHANNEL				"subchannel"

#define SENSYSMSG_DIAGNOSTIC_SENSORID				"sensorId"
#define SENSYSMSG_DIAGNOSTIC_TIMESTAMP				"timestamp"
#define SENSYSMSG_DIAGNOSTIC_STATUS					"status"
#define SENSYSMSG_DIAGNOSTIC_ADDRESS1				"address1"
#define SENSYSMSG_DIAGNOSTIC_SUBCHANNEL				"subchannel"
#define SENSYSMSG_DIAGNOSTIC_IDLE					"idle"
#define SENSYSMSG_DIAGNOSTIC_DIAG					"diag"

#define	SENSYSMSG_MAX_STRING_LEN					16

char messageTypes[NUMBER_OF_MSG_TYPES][SENSYSMSG_MAX_STRING_LEN] = 
{
	{SENSYS_MSG_TYPE_EVENT},{SENSYS_MSG_TYPE_WATCHDOG},{SENSYS_MSG_TYPE_DIAGNOSTIC}/*Add new message types here*/
};

char sensysMsgParameters[NUMBER_OF_MSG_TYPES][NUMBER_OF_EVENT_PARAMETERS][SENSYSMSG_MAX_STRING_LEN] =
{
	{SENSYSMSG_EVENT_SENSORID,SENSYSMSG_EVENT_TIMESTAMP,SENSYSMSG_EVENT_STATUS,SENSYSMSG_EVENT_ADDRESS1,SENSYSMSG_EVENT_SUBCHANNEL,SENSYSMSG_EVENT_ADJUSTED,SENSYSMSG_EVENT_DIRECTION},

	{SENSYSMSG_WATCHDOG_SENSORID,SENSYSMSG_WATCHDOG_TIMESTAMP,SENSYSMSG_WATCHDOG_STATUS,SENSYSMSG_WATCHDOG_ADDRESS1,SENSYSMSG_WATCHDOG_SUBCHANNEL},

	{SENSYSMSG_DIAGNOSTIC_SENSORID,SENSYSMSG_DIAGNOSTIC_TIMESTAMP,SENSYSMSG_DIAGNOSTIC_STATUS,SENSYSMSG_DIAGNOSTIC_ADDRESS1,SENSYSMSG_DIAGNOSTIC_SUBCHANNEL,SENSYSMSG_DIAGNOSTIC_IDLE,SENSYSMSG_DIAGNOSTIC_DIAG}
	
	//Add new message type parameters here. Order of these parameters is important and related to messageTypes array above.
};